
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'Glovo' do
  pod 'GoogleMaps'
  pod 'RealmSwift'

  target 'GlovoTests' do
      inherit! :search_paths
  end
end
